### PR TITLE
Rename DER option

### PR DESCRIPTION
**Pull request by CovenEsme**
Renames the "All Dungeons" DER setting to "All Surface Dungeons" to better describe its behaviour

### CODE REVIEW

**Review by cjs8487 — COMMENTED** [review]
Should we also rename "All Dungeons + Sky Keep" -> "All Dungeons"

**Comment by CovenEsme** [comment]
I thought about that but since we don't treat Sky Keep as a proper dungeon (like, it can't be one of the required dungeons), I think it's clearer to keep that as is?

**Comment by cjs8487** [comment]
Yeah that's a fair point. If we want to keep " + Sky Keep" maybe we should change it to "All Surface Dungeons + Sky Keep"? Makes it a bit clearer that the only change is adding Sky Keep into the mix, but I don't really mind either way

**Comment by CovenEsme** [comment]
Cool, works for me

**Comment by CovenEsme** [comment]
Will require a tracker update when this gets merged :p

**Pull request merged**
